#!/bin/bash

# Get the C file name from the environment variable
c_file=$CFILE

# Generate the assembly code
gcc -S -masm=intel "$c_file"

# Create the output file name by replacing the .c extension with .s
output_file="${c_file%.c}.s"

# Move the generated assembly code to the output file
mv "${c_file%.c}.s" "$output_file"
